apiVersion: apps/v1
kind: Deployment
metadata:
  name:  offer-service-deployment
  namespace: default
  labels:
    app:  offer-service
spec:
  selector:
    matchLabels:
      app: offer-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  offer-service
    spec:
      initContainers: 
      - name: init-rabbitmq-service
        image: busybox 
        command: ['sh','-c', 'until nslookup rabbitmq-service.default.svc.cluster.local; do echo waiting for rabbitmq service to come up; sleep 2; done;'] 

      containers:
      - name:  offer-service-container
        image: ghcr.io/jadonharsh109/istio-microservice-deployment-offer:latest
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8082
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 3
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort:  8082
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: offer-service
  namespace: default
  labels:
    app: offer-service
spec:
  selector:
    app: offer-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP