apiVersion: apps/v1
kind: Deployment
metadata:
  name:  service-registry-deployment
  namespace: default
  labels:
    app:  service-registry
spec:
  selector:
    matchLabels:
      app: service-registry
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  service-registry
    spec:
      containers:
      - name:  service-registry-container
        image: ghcr.io/jadonharsh109/istio-microservice-deployment-registry:latest
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8000
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 3
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort:  8761
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: default
  labels:
    app: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP